dist: bionic
sudo: required
services:
  - docker

notifications:
  email: false

script:
  - docker build -t $DOCKER_ID/backend:latest -f ops/Dockerfile .

after_success:
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_ID --password-stdin
  - docker push $DOCKER_ID/backend:latest 

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "backend"
  env: "Backend-env"
  bucker_name: "elasticbeanstalk-ap-southeast-1-478286478079"
  bucker_path: "backend"
  on:
    branch : master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_ACCESS_SECRET