dist: bionic
sudo: required
services:
  - docker

notifications:
  email: false

script:
  - docker build -t $DOCKER_ID/backend:latest -f ./ops/production/Dockerfile .

after_success:
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_ID --password-stdin
  - docker push $DOCKER_ID/backend:latest 

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: $AWS_EB_APP
  env: $AWS_EB_ENV
  bucker_name: $AWS_BUCKER_NAME
  bucker_path: backend
  on:
    branch : master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_ACCESS_SECRET