version: '3'

services:
  backend-beego:
    container_name: "backend-beego"
    build:
      context: .
      dockerfile: ./ops/development/Dockerfile
    volumes:
      - ./beego:/go/src/backend
    env_file:
      - ./ops/development/beego.env
    ports:
      - "8081:8080"
    restart: always
    networks:
      - "backend-network"

  backend-mysql:
    container_name: "backend-mysql"
    image: mysql
    restart: always
    env_file:
      - ./ops/development/db.env
    networks:
      - "backend-network"

  backend-adminer:
    container_name: "backend-adminer"
    image: adminer
    ports:
      - 8082:8080
    networks:
      - "backend-network"

networks:
  backend-network:
    driver: "bridge"
