version: '3'

services:
  backend-beego:
    container_name: "backend-beego"
    build:
      context: .
      dockerfile: ./ops/Dockerfile
    ports:
      - "8081:8080"
    # restart: always
    networks:
      - "backend-network"

  backend-mysql:
    container_name: "backend-mysql"
    image: mysql
    restart: always
    ports:
      - "33066:3306"
    env_file:
      - ./ops/db/.env
    networks:
      - "backend-network"

  backend-adminer:
    container_name: "backend-adminer"
    image: adminer
    ports:
      - 8082:8080
    networks:
      - "backend-network"

networks:
  backend-network:
    driver: "bridge"
