version: '3'

services:
  backend-beego:
    container_name: "backend-beego"
    build: ./beego/ops
    volumes:
      - "./beego/src:/go/src/backend"
      - "./vuejs:/vuejs/"
    ports:
      - "8081:8080"
    links:
      - "backend-mysql"
    depends_on:
      - "backend-mysql"

  backend-mysql:
    container_name: "backend_mysql"
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./db/.env

  backend-adminer:
    container_name: "backend-adminer"
    image: adminer
    ports:
      - 8082:8080
